### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by gbaruffa** [loraraspi91/LoRa4Raspi#2]
Hello,
I was wondering whether it is normal to have a 100% CPU usage when running the receivers on a Raspberry Pi Zero W, or 30% on a Raspberry Pi 3 Mod B. I have tried both the LoRaReceiver and LoRaReceiverCallback programs. BTW, I am using this with an Adafruit LoRa Radio Bonnet with OLED and, apart the high CPU usage, it seems to work fine. I am instantiating the module with

```
...
LoRa.setPins(11, 6, 3);
...
```

in the code.

**Comment by loraraspi91** [comment]
Hello,

Yes it is normal since the example make an infinite loop without any delay
or sleep
You can change the program by adding a "sleep" instruction to make the cpu
breathing.

**Comment by loraraspi91** [comment]
You can also use the example "callback" it makes receipt or sending message
via interrupt. So no cpu is used to wait for an incomming message.
The library working exactly like the original library in term of cpu usage

Le dim. 19 juil. 2020 à 12:17, laurent Rioux <loraraspi91@gmail.com> a
écrit :

**Comment by gbaruffa** [comment]
Nice, thank you! I have put the CPU to sleep within the ``loop()`` function
```
#include <unistd.h>
...
void loop() {
  ...
  usleep(50000);
  ...
}
...
```
and now the loads are normalized (<1%).
