### ISSUE TITLE
Negative SNR mapped into unsigned int.

### ISSUE THREAD

**Issue by alecks68** [loraraspi91/LoRa4Raspi#3]
Thanks for this nice work! I am using it with HopeRF RFM95W and it works nicely.

In function packetSnr() you should replace casting to (uint8_t) into (int8_t).
The RFM95W Datasheet says:

![image](https://user-images.githubusercontent.com/38050497/208257037-8f0b449a-9c55-4fb7-87f4-3daf6f70ff75.png)

You can also consider to call sleep in the loop at least for the CallBack example:
void loop() {
// just waiting  onReceive callback; nothing done here
sleep(60000);
}

**Comment by loraraspi91** [comment]
Thanks you for your feedbacks

Changes done.
